spring.application.name=portfolio-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_cms
spring.datasource.username=postgres
spring.datasource.password=mayank


#jwt.secret=ajsjfhaurrhueaksgaisgfkas
jwt.secret=MyPortfolioCMSSecretKey2026SecureAuthenticationKey
jwt.expiration=86400000


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

aws.s3.bucket-name=mayank-portfolio-cms-2026
aws.s3.region=ap-south-1
aws.access-key=AKIAQ3EGUP4IMPXYUUN3
aws.secret-key=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

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

